---
title: "Mouse Gastrulation scRNA-seq Data Analysis"
output: html_document
Author: Huei Teng Ng
---

The code below showed re-analysis pipeline of mouse gastrulation scRNA-seq data generated by Pijuan-Sala et al. 2019 https://doi.org/10.1038/s41586-019-0933-9. 
```{r}
library(ggplot2)
library(MouseGastrulationData)
library(scuttle)
library(tidyverse)
library(AUCell)
library(GSEABase)
library(paletteer)
library(ggpubr)


##E6.5----
#read data from MouseGastrulationData
metadata<- AtlasSampleMetadata #metadata
stage_65<- EmbryoAtlasData(type = 'processed', samples = c(1,5,18))

stage_65_colData<- as.data.frame(as.matrix(colData(stage_65)))
stage_65_colData<- subset(stage_655_colData,is.na(stage_65_colData$celltype)==F) #remove bad quality cells

stage_65_rowData<- as.data.frame(as.matrix(rowData(stage_65)))
stage_65_count<-logNormCounts(stage_65) #normalise counts
stage_65_count<- logcounts(stage_65_count) #extract normalised counts
stage_65_count<- as.data.frame(as.matrix(stage_65_count))
stage_65_count<- as.data.frame(t(stage_65_count))
colnames(stage_65_count)<- subset(stage_65_rowData,ENSEMBL %in% colnames(stage_65_count))$SYMBOL
E65_Wt1<- t(subset(stage_65_count,`Wt1`>0)) #subset cells with Wt1 expression >0 
head(E65_Wt1['Wt1',],n=10)

```

```{r}
#define gene sets
SMC_genes<- c('Ppp1r12b', 'Lmod1', 'Myl9', 'Tpm2', 'Actg2', 'Cnn1', 'Tagln', 'Myh11', 'Mylk', 'Acta2', 'Flna',
              'Mrtfa','Mrtfb','Pdgfrb','Bmp4')
SMC_genes<- GeneSet(SMC_genes, setName ='SMC_geneSet')
Meso_genes<- c('Aldh1a2', 'Prrx2', 'Rspo1', 'Upk3b', 'Wnt2b', 'Msln', 'Fgf18', 'Muc16', 'Lrrn4','Meis3','Gata5','Gata6','Tcf21','Tbx18','Pdpn')
Meso_genes<- GeneSet(Meso_genes, setName ='Mesothelial_geneSet')
GeneSets<- GeneSetCollection(SMC_genes, Meso_genes)

#run AUCell- calculate the signature enrichment scores on each cell 
E65_cells_AUC <- AUCell_run(E65_Wt1, GeneSets) #save this for downstream analysis

load(file="~/R script/Mouse_Gastrulation_sc/E6.5_cells_AUC.RData") #load my saved file
```
```{r}
# the function AUCell_exploreThresholds() automatically plots all the histograms and calculates several thresholds that could be used to consider a gene-set ‘active’ (returned in $aucThr).
set.seed(335)
par(mfrow=c(1,2))
E65_cells_assignment <- AUCell_exploreThresholds(E65_cells_AUC, plotHist=TRUE, assign=TRUE)

#view threshold options
E65_cells_assignment[["SMC_geneSet"]][["aucThr"]]
E65_cells_assignment[["Mesothelial_geneSet"]][["aucThr"]]

```
```{r}
#define selected threshold
newThres<- getThresholdSelected(E65_cells_assignment)
newThres['SMC_geneSet']=0.0097
newThres['Mesothelial_geneSet']=0.0036
new_E65_assignment<- AUCell_assignCells(E65_cells_AUC,newThres)

```

```{r}
#repeat steps above for E7.5 and E8.5- I am loading my saved files below
#E7.5
load(file="~/R script/Mouse_Gastrulation_sc/E7.5_cells_AUC.RData")
set.seed(333)
par(mfrow=c(1,2))
E75_cells_assignment <- AUCell_exploreThresholds(E75_cells_AUC, plotHist=TRUE, assign=TRUE) 
newThres<- getThresholdSelected(E75_cells_assignment)
newThres['SMC_geneSet']=0.044
newThres['Mesothelial_geneSet']=0.011
new_E75_assignment<- AUCell_assignCells(E75_cells_AUC,newThres)


#E8.5
load(file="~/R script/Mouse_Gastrulation_sc/E8.5_cells_AUC.RData")
set.seed(344)
par(mfrow=c(1,2))
E85_cells_assignment <- AUCell_exploreThresholds(E85_cells_AUC, plotHist=TRUE, assign=TRUE)
newThres<- getThresholdSelected(E85_cells_assignment)
newThres['SMC_geneSet']=0.198
newThres['MC_geneSet']=0.0565
new_E85_assignment<- AUCell_assignCells(E85_cells_AUC,newThres)

```
```{r}
#Signature plot####
sig_table<-data.frame(matrix(ncol = 4, nrow = 0))

#compile signature scores into one dataframe
assignment_list<- list(new_E75_assignment,new_E85_assignment,new_E65_assignment)
names(assignment_list)<-c('E7.5','E8.5','E6.5')  

for(i in c('E6.5','E7.5','E8.5')){
  for(geneset in c('SMC_geneSet','Mesothelial_geneSet')){
    data<- assignment_list[[i]]
    ncells<-length(data[[geneset]][["assignment"]])
    AUC<- data[[geneset]][["aucThr"]][["selected"]][[geneset]]
    meta<- c(AUC,ncells,i,geneset)
    sig_table<-rbind(sig_table,meta)
    
  }
}
colnames(sig_table)<-c('Score','nCells','Timepoint','geneSet')
sig_table[,c('nCells','Score')]<- sapply(sig_table[,c('nCells','Score')], function(x) as.numeric(x))

#calculate cell ratio
for(x in 1:6){
  if(sig_table$Timepoint[x]=='E7.5'){
    sig_table$cell_ratio[x]<-sig_table$nCells[x]/118 #divide by total number of Wt1+ cells
  }
  else if(sig_table$Timepoint[x]=='E8.5'){
    sig_table$cell_ratio[x]<-sig_table$nCells[x]/284
  }
  else if (sig_table$Timepoint[x]=='E6.5'){
    sig_table$cell_ratio[x]<-sig_table$nCells[x]/53
  }
  else{next}
}

sc <- scale_colour_gradientn(colours = rev(paletteer_c("grDevices::Dark Mint", 50)), limits=c(0.001,0.25))
sig_table$geneSet<-str_replace_all(sig_table$geneSet,'Mesothelial_geneSet','MC_geneSet')

ggplot(sig_table, aes(x=Timepoint, y=geneSet)) + geom_point(aes(size=cell_ratio,colour=Score))+
  theme_bw()+scale_size(range = c(4,18))+ sc+ 
  theme(axis.title.y = element_blank(), axis.text = element_text(size=11),legend.text = element_text(size=11), axis.title.x = element_blank(), axis.text.x=element_text(, angle = 90))+
  xlab('Stage')


```
```{r}
#view details of cells passed threshold####
#E7.5
stage_75<- EmbryoAtlasData(type = 'processed', samples = c(2:4,6,19,20))
stage_75_colData<- as.data.frame(as.matrix(colData(stage_75)))
stage_75_colData<- subset(stage_75_colData,is.na(stage_75_colData$celltype)==F) #remove bad quality cells
E75_SMC_ID<-new_E75_assignment[["SMC_geneSet"]][["assignment"]] #cell ID 
E75_SMC<-subset(stage_75_colData, cell%in%E75_SMC_ID)
E75_SMC

```
```{r}
#E8.5
stage_85<- EmbryoAtlasData(type = 'processed', samples = c(17,29,36,37))
stage_85_colData<- as.data.frame(as.matrix(stage_85@colData))
stage_85_colData<- subset(stage_85_colData,is.na(stage_85_colData$celltype)==F) #remove bad quality cells
E85_SMC_ID<-new_E85_assignment[["SMC_geneSet"]][["assignment"]] #cell ID 
E85_SMC<-subset(stage_85_colData, cell%in%E85_SMC_ID)
E85_SMC
```
```{r}
#check if there's any overlapping celss between two groups
#E7.5
E75_overlap<- intersect(new_E75_assignment[["SMC_geneSet"]][["assignment"]],new_E75_assignment[["Mesothelial_geneSet"]][["assignment"]])
E75_overlap<- subset(stage_75_colData, cell%in%E75_overlap)
E75_overlap_venn<- list('SMC'=new_E75_assignment[["SMC_geneSet"]][["assignment"]], 'MC'=new_E75_assignment[["Mesothelial_geneSet"]][["assignment"]])
ggvenn::ggvenn(E75_overlap_venn,fill_color = c("#7AC5CD", "#EEE8CD"),text_size = 11, show_percentage = F)

#E8.5
E85_overlap_venn<- list('SMC'=new_E85_assignment[["SMC_geneSet"]][["assignment"]], 'MC'=new_E85_assignment[["Mesothelial_geneSet"]][["assignment"]])
E85_overlap<- intersect(E85_overlap_venn$SMC,E85_overlap_venn$MC)
E85_overlap<- subset(stage_85_colData, cell%in%E85_overlap)
ggvenn::ggvenn(E85_overlap_venn,fill_color = c("#7AC5CD", "#EEE8CD"),text_size = 11, show_percentage = F)

```
```{r}
#Compare Wt1 expression of cells in SMC & Mesothelial signature####
##E8.5

SMC_cells<-as.data.frame(new_E85_assignment[["SMC_geneSet"]][["assignment"]])
colnames(SMC_cells)<-'SMC_cells'
SMC_cells<- subset(SMC_cells, !SMC_cells%in% E85_overlap$cell) #remove overlapped cells
SMC_cells<- subset(master_table, cell%in%SMC_cells$SMC_cells)
SMC_cells$Group_med<-median(SMC_cells$Wt1)

for(row in 1:nrow(SMC_cells)){
  if(SMC_cells[row,'celltype']=='Mesenchyme/LPM'){
    SMC_cells$celltype_2[row]<-'Mesenchyme/LPM'
  }
  else{
    SMC_cells$celltype_2[row]<-'Other cell types' 
  }
}

Meso_cells<-as.data.frame(new_E85_assignment[["Mesothelial_geneSet"]][["assignment"]])
colnames(Meso_cells)<-'Meso_cells'
Meso_cells<- subset(Meso_cells, !Meso_cells%in% E85_overlap$cell) 
Meso_cells<- subset(master_table, cell%in%Meso_cells$Meso_cells)
Meso_cells$Group_med<-median(Meso_cells$Wt1)

for(row in 1:nrow(Meso_cells)){
  if(Meso_cells[row,'celltype']=='Mesenchyme/LPM'){
    Meso_cells$celltype_2[row]<-'Mesenchyme/LPM'
  }
  else{
    Meso_cells$celltype_2[row]<-'Other cell types' 
  }
}

#colour of celltype
myColour_Wt1<- c('#1F8F99','grey')

names(myColour_Wt1) <- unique(Meso_cells$celltype_2)
mycolScale_Wt1 <- scale_colour_manual(name = "celltype",values = myColour_Wt1)

ggplot(Meso_cells, aes(x=cell,y=Wt1,colour=celltype_2))+ geom_point(size=2)+ theme_light()+
  theme(axis.text.x = element_blank(), legend.text = element_text(size=11), legend.title = element_text(size=11), axis.text.y=element_text(size=11))+ 
  labs(title='MC')+
  geom_hline(aes(yintercept = Group_med), linetype='dashed')+ ylim(0,2.8)+ scale_color_manual(name = "Cell Type",values = myColour_Wt1)

ggplot(SMC_cells, aes(x=cell,y=Wt1, colour=celltype_2))+ geom_point(size=2)+ theme_light()+
  theme(axis.text.x = element_blank(), legend.text = element_text(size=11), legend.title = element_text(size=11), axis.text.y=element_text(size=11))+ ylim(0,2.8)+
  labs(title='SMC')+
  geom_hline(aes(yintercept = Group_med), linetype='dashed')+ scale_color_manual(name = "Cell Type",values = myColour_Wt1)


```


